# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: pizzafrontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on:
      - backend
  backend:
    image: pizzabackend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5900:80"